# Generated by Django 2.0.2 on 2018-03-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studteach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='attendance',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
